#!/bin/bash
#=======================================================================
# Save error stream to a file
#=======================================================================
test $# -ge 2 || { echo "Usage: $0 file cmd..." >&2; exit 2; }
filename=$1; shift

exec 3>&1
"$@" 2>&1 >&3 | tee "$filename" >&2

x0=${PIPESTATUS[0]}
exit $x0
