#!/bin/sh
pkg="$1"
if [ -f "/usr/bin/dpkg-query" ]; then
    dpkg-query -L "$pkg"
elif [ -f "/bin/rpm" -o -f "/usr/bin/rpm" ]; then
    rpm -ql "$pkg"
else
    echo "$0: Unknown packaging" >&2
    exit 1
fi
