#!/bin/sh
test $# -gt 1 || { echo "Usage: $0 venvname cmd..." >&2; exit 2; }
name=$1; shift

venvdir="$HOME/venv/$name"
test -d "$venvdir" || { echo "No such venv $name" >&2; return 1; }
. "$venvdir/bin/activate"
"$@"
