#!/usr/bin/env python
#=======================================================================
"""
Plot signals from text file
"""
#=======================================================================

def main():
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument('-x', action='store_true',
                    help='Assume first column is X (typically time)')
    ap.add_argument('-t','--title',
                    help='Title for graph')
    ap.add_argument('-l','--label', action='append', default=[],
                    help='Label for each column')
    ap.add_argument('filename', nargs='?',
                    help='File containing value (default: stdin)')
    args = ap.parse_args()
    filename = args.filename
    if filename in (None, '-'):
        filename = '/dev/stdin'

    try:
        rows = []
        lineno = 0
        with open(filename, 'r') as f:
            ncols = None
            for line in f:
                lineno += 1
                try:
                    row = [float(v) for v in line.split()]
                except ValueError as e:
                    raise ValueError('%s:%d: %s' % (filename,lineno, e)) \
                        from None
                if ncols is None:
                    ncols = len(row)
                    if ncols == 0:
                        raise ValueError('%s:%d: No data' % (filename, lineo))
                elif len(row) != ncols:
                    raise ValueError('%s:%d: %d column(s), previously %d' %
                                     (filename, lineno, len(row), ncols))
                rows.append(row)
    except Exception as e:
        ap.error(str(e))

    # Transpose
    cols = list(zip(*rows))
    if args.x:
        if len(cols) < 2:
            raise ValueError('Only one column; expected >= 2 for -x option')
        x = cols.pop(0)
    else:
        x = list(range(len(rows)))

    plot = Plot(title=args.title)
    for i, col in enumerate(cols):
        try:
            label = args.label[i]
        except IndexError:
            label = None
        plot.add(x, col, title=label)
    plot.show()

class Plot:
    """Graphical plot of one or more signals"""
    # Loosely based on gplot.py from https://github.com/mzechmeister/python
    def __init__(self, title=None, ylabel=None):
        self.title = title
        self.ylabel = ylabel
        self.tmpfiles = []
        self.plots = []

    colours = ('blue','red','green','yellow','orange','orchid','brown')

    def set_ylabel(self, ylabel):
        self.ylabel = ylabel

    def add(self, xvalues, yvalues, title=None, colour=None):
        index = len(self.plots)
        if title is None:
            title = f'data{1+index}'
        if colour is None:
            colour = self.colours[index % len(self.colours)]
        import tempfile
        tmp = tempfile.NamedTemporaryFile(mode='w+', encoding='utf8',
                                          delete=True)
        self.tmpfiles.append(tmp)
        for x, y in zip(xvalues, yvalues):
            print(f'{x} {y}', file=tmp)
        tmp.flush()
        plot = f'"{tmp.name}" title "{title}"'
        plot += f' with linespoints linetype 3 linecolor rgb "{colour}"'
        self.plots.append(plot)

    def add_vbar(self, x, yrange, title=None, colour='black'):
        """Add a vertical bar e.g. to highlight a significant time"""
        if title is None:
            title = str(to_us(x)/1e6)
        ymin, ymax = yrange
        plot = f'[{ymin}:{ymax}] {x},t title "{title}" with lines linecolor rgb "{colour}"'
        self.plots.append(plot)

    def show(self):
        if not self.plots:
            raise ValueError('No plots to show')
        import subprocess
        self.proc = subprocess.Popen(['gnuplot'],
                                     stdin=subprocess.PIPE,
                                     universal_newlines=True,
                                     bufsize=0)
        if self.title is not None:
            self.put(f'set title "{self.title}"')
        if self.ylabel is not None:
            self.put(f'set ylabel "{self.ylabel}"')
        self.put('set parametric') # E.g. for vbar
        cmd = 'plot ' + ', '.join(self.plots)
        self.put(cmd)
        self.put('pause mouse close')
        self.proc.stdin.close()
        self.proc.wait()

    def put(self, command):
        print(command, file=self.proc.stdin)

    def __del__(self):
        # Tidy up temporary files
        while self.tmpfiles:
            tmp = self.tmpfiles.pop()
            tmp.close()
            del tmp

if __name__=='__main__':
    main()
